### ISSUE TITLE
ローカルでctfサイトを動作させる

### ISSUE THREAD

**Issue by kazutxt** [zunda-cafe/ctf#4]
python,Django,開発環境を整備して、ローカルでCTFサイトを開発できるようにする
- [x] @naninuneter55 
- [x] @f91seed 
- [x] @maruhachi 
- [x] @kazutxt

**Comment by yk0nno** [comment]
* 動きました🚀 

若干修正が必要な点がありました。CTFで使うバージョンが決まり、必要ならこの内容のPRを送ります。
[Django起動方法](https://github.com/zunda-cafe/zunda-cafe/issues/1)に従いセットアップしてみましたが、` python manage.py redmine_migration` のコマンド実行時にエラーが出ました。

```python
  File "C:\konno\src\ctf\challenge\management\commands\redmine_migration.py", line 4, in <module>
    from redmine import Redmine
ModuleNotFoundError: No module named 'redmine'
```
自分の環境では`pip install python-redmine`するとver2.0.2が入ってきました。
どうやら[ver2からパッケージ名が変わった](https://pypi.python.org/pypi/python-redmine/2.0.0#changelog)ようです。修正内容はこちら。
```diff
$ g diff challenge/management/commands/redmine_migration.py
diff --git a/challenge/management/commands/redmine_migration.py b/challenge/management/commands/redmine_migration.py
index 85b84a9..3cd64a8 100755
--- a/challenge/management/commands/redmine_migration.py
+++ b/challenge/management/commands/redmine_migration.py
@@ -1,7 +1,7 @@
 #! /bin/python

 from django.core.management.base import BaseCommand
-from redmine import Redmine
+from redminelib import Redmine
```

* とりあえず開発は出来るようになりましたが、対向となるお試し用redmineが欲しいかも。
  * ただRESTを飛ばしてるだけならダミーレスポンスするスタブでも?

**Comment by naninuneter55** [comment]
色々とご迷惑をおかけしています。
今回のCTFの作り直しでは基本的にRedmineは使用しません。ただし旧版のCTFがRedmineをDBとして使用していたため、問題データをRemineからSQLite に移行するスクリプトを /challenge/management/commands/redmine_migration.py に作りました。
モダンな開発を体験するという我々の中では必要のないスクリプトだと思いますので、python-redmine モジュールは入れなくてもいいかなと思います。
python manage.py redmine_migration　が移行スクリプト実行コマンドです。これも実行不要です。
すみません。

**Comment by yk0nno** [comment]
承知しました。　そういった背景だったんですね。物は試しとcommand.txtに追従してみてました。
であれば自分は起動確認完了です 👍 
~追ってる中でpythonのパッケージ管理の勉強になりました笑~

**Comment by naninuneter55** [comment]
slack連携のテスト

**Comment by yk0nno** [comment]
* Windowsでの参考サイト
[Qiita - Python Django入門 (2) Win編](http://qiita.com/kaki_k/items/1fff7fefcf26dc4b69bc#%E4%BB%AE%E6%83%B3%E7%92%B0%E5%A2%83%E3%81%AE%E6%A7%8B%E7%AF%89---virtualenv%E7%B7%A8)
